apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference-control-plane
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - postgres-backup-cronjob.yaml
  - pvc.yaml
  - redis.yaml
  - app-deployment.yaml
  - app-service.yaml
  - hpa.yaml
  - pdb.yaml
  - prometheus-config.yaml
  - prometheus.yaml
