apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inference-control-plane.fullname" . }}-postgres-backup-pvc
  labels:
    app: {{ include "inference-control-plane.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
